baseURL = "http://nehasatapathy.com/"
languageCode = "en-us"
title = "Neha Satapathy"
theme = "dream"
googleAnalytics = "UA-176280849-1"


[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  background = "black"
  # backgroundImage = "/pika2.jpg"
  linkColor = "#9B59B6"

  author = "nehaha"
  description = "NEHA SATAPATHY"
  avatar = "/pika2.jpg"
  motto = "Strong type A-/B+ personality"
  categoriesLimitInHeader = 6
  # headerBottomText = ""

  rss = true

  # utterancesRepo = "g1eny0ung/g1eny0ung.github.io"

  email = "n.satapathy02@gmail.com"
  twitter = "nehaha_"
  # facebook = ""
  instagram = "nehaha_"
  linkedin = "nehasatapathy"
  github = "nehaha"
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2020

  favicon = "/favicon.ico"

  highlightjs = true
  #highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["ocaml"]
  highlightjsTheme = "gruvbox-light"
  highlightjsThemeDark = "gruvbox-dark"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = true

  # dark mode
  darkLinkColor = "#BB8FCE"
  darkNav = true
  dark404 = true